apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: my-terraform-resource
  namespace: flux-system
spec:
  interval: 1m
  approvePlan: auto
  destroyResourcesOnDeletion: true
  path: /home/trainer/gitops-repo/flux-clusters/dev-cluster/terraform/azure/storage-account
  sourceRef:
    kind: GitRepository
    name: flux-system
